[profile.default]
src = "src"
out = "out"
libs = ["lib"]

remappings = [
  '@openzeppelin/contracts=lib/openzeppelin-contracts/contracts/',
  '@openzeppelin/contracts-upgradeable=lib/openzeppelin-contracts-upgradeable/contracts',
]

[rpc_endpoints]
anvil = "http://127.0.0.1:8545"
sepolia = "https://eth-sepolia.g.alchemy.com/v2/${ALCHEMY_KEY}"
arbSepolia = "https://arb-sepolia.g.alchemy.com/v2/${ALCHEMY_KEY}"
opSepolia = "https://opt-sepolia.g.alchemy.com/v2/${ALCHEMY_KEY}"

[etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}" }
arbSepolia = { key = "${ETHERSCAN_API_KEY}" }
opSepolia = { key = "${ETHERSCAN_API_KEY}" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
